name: Qadeer Khan
title: Qadeer Khan | Manager Technology | Product Development
description: Manager Technology at ACE Money Transfer | Fintech | Financial Services | e-money | Wallets | Accounting Solutions
url: https://imqadeerkhan.github.io/
baseurl: ''
email: qadeer@withgale.com
cover: https://imqadeerkhan.github.io/img/og.png
logo: https://imqadeerkhan.github.io/img/emojis/technologist.png
social:
  - title: email
    url: mailto:qadeer@withgale.com
  - title: twitter
    url: https://twitter.com/imqadeerkhan
  - title: github
    url: https://github.com/imqadeerkhan
  - title: linkedin
    url: https://www.linkedin.com/in/imqadeerkhan/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
